__version__ = "0.4.5"

from heavystats.validation import ValidationReport, validate_data
from heavystats.comparation import (
    ComparationReport,
    compare_groups,
)
from heavystats.cleaning import (
    VariableTypeReport,
    VariablesTableReport,
    columns_type,
    categorical_columns,
    numerical_columns,
    variables_table,
    get_analytical_sample,
    select_metal,
    load_data,
    standardize_boolean_columns,
    desaggregate_multiple_responses,
    encode_dietary_frequencies,
    create_composite_indicators,
)
from heavystats.univariate import (
    BasePlots,
    UnivariateTables,
    UnivariatePlots,
    desglosar_multirrespuesta,
    obtener_mascara_percentiles,
    DEFAULT_LABELS_MAP,
    DEFAULT_CUSTOM_PARAMS,
    DEFAULT_PERMISSIBLE_LIMITS,
    CDC_BMI_REFERENCE,
    get_label,
)
from heavystats.bivariate import (
    BivariatePlots,
    compare_groups_plot,
    correlation_analysis_plot,
    coexposure_matrix_plot,
    diet_radar_plot,
    diet_boxplots_plot,
    similarity_ranking_plot,
    subcohort_contrast_plot,
    shared_factors_plot,
    subcohort_mosaic_plot,
    survey_block_heatmap_plot,
    survey_radiography_plot,
    survey_synthesis_plot,
    scan_subcohort_contrasts,
    comparar_grupos_plot,
    correlacion_analisis_plot,
    matriz_coexposicion_plot,
    radar_dietario_plot,
    mosaico_dietario_plot,
    ranking_similitud_plot,
    contraste_subcohorte_plot,
    factores_compartidos_plot,
    mosaico_subcohorte_plot,
    radiografia_encuesta_plot,
    sintesis_encuesta_plot,
    mann_whitney_test,
    independent_t_test,
    kruskal_wallis_test,
    anova_oneway_test,
    dunn_posthoc_test,
    jonckheere_terpstra_test,
    spearman_correlation,
    pearson_correlation,
    kendall_correlation,
    spearman_matrix,
    adjust_pvalues,
    hodges_lehmann_2sample,
    bootstrap_ci_diff_medians,
    DEFAULT_METAL_LIMITS,
    DEFAULT_METAL_LODS,
    DEFAULT_METAL_CUTOFFS,
    DEFAULT_METAL_PAIRS,
)
from heavystats.multivariante import (
    MultivariatePipeline,
    MultivariateScreening,
    LassoModeler,
    PlsModeler,
    MultivariateTableReport,
)
from heavystats.version_checker import check_for_updates

__all__ = [
    "__version__",
    "ValidationReport",
    "validate_data",
    "ComparationReport",
    "compare_groups",
    "VariableTypeReport",
    "VariablesTableReport",
    "columns_type",
    "categorical_columns",
    "numerical_columns",
    "variables_table",
    "get_analytical_sample",
    "select_metal",
    "load_data",
    "standardize_boolean_columns",
    "desaggregate_multiple_responses",
    "encode_dietary_frequencies",
    "create_composite_indicators",
    "BasePlots",
    "UnivariateTables",
    "UnivariatePlots",
    "desglosar_multirrespuesta",
    "obtener_mascara_percentiles",
    "BivariatePlots",
    "compare_groups_plot",
    "correlation_analysis_plot",
    "coexposure_matrix_plot",
    "diet_radar_plot",
    "diet_boxplots_plot",
    "similarity_ranking_plot",
    "subcohort_contrast_plot",
    "shared_factors_plot",
    "subcohort_mosaic_plot",
    "survey_block_heatmap_plot",
    "survey_radiography_plot",
    "survey_synthesis_plot",
    "scan_subcohort_contrasts",
    "comparar_grupos_plot",
    "correlacion_analisis_plot",
    "matriz_coexposicion_plot",
    "radar_dietario_plot",
    "mosaico_dietario_plot",
    "ranking_similitud_plot",
    "contraste_subcohorte_plot",
    "factores_compartidos_plot",
    "mosaico_subcohorte_plot",
    "radiografia_encuesta_plot",
    "sintesis_encuesta_plot",
    "mann_whitney_test",
    "independent_t_test",
    "kruskal_wallis_test",
    "anova_oneway_test",
    "dunn_posthoc_test",
    "jonckheere_terpstra_test",
    "spearman_correlation",
    "pearson_correlation",
    "kendall_correlation",
    "spearman_matrix",
    "adjust_pvalues",
    "hodges_lehmann_2sample",
    "bootstrap_ci_diff_medians",
    "DEFAULT_LABELS_MAP",
    "DEFAULT_CUSTOM_PARAMS",
    "DEFAULT_PERMISSIBLE_LIMITS",
    "DEFAULT_METAL_LIMITS",
    "DEFAULT_METAL_LODS",
    "DEFAULT_METAL_CUTOFFS",
    "DEFAULT_METAL_PAIRS",
    "CDC_BMI_REFERENCE",
    "get_label",
    "MultivariatePipeline",
    "MultivariateScreening",
    "LassoModeler",
    "PlsModeler",
    "MultivariateTableReport",
    "check_for_updates",
    "launch_studio",
]


def launch_studio():
    """Lanza la interfaz de usuario de terminal interactiva de HeavyStats Studio."""
    from heavystats.studio.app import iniciar_tui
    return iniciar_tui()

# Verificación de versiones no bloqueante en segundo plano al importar
try:
    check_for_updates(__version__, async_check=True)
except Exception:
    pass


def __getattr__(name: str):
    if name == "df":
        from heavystats.cleaning import df
        return df
    raise AttributeError(f"module {__name__} has no attribute {name}")
